[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/apps.html"
  to = "/apps"
  status = 301
  force = true

[[redirects]]
  from = "/gxmes.html"
  to = "/games"
  status = 301
  force = true

[[redirects]]
  from = "/gxmes"
  to = "/games"
  status = 301
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404